apiVersion: v1
kind: List
spec: {}
items:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: tempapp
  spec: {}
  status: {}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    namespace: tempapp
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: temps
      app.kubernetes.io/component: temps
      app.kubernetes.io/instance: temps
    name: temps
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    namespace: tempapp
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: temps
      app.kubernetes.io/component: temps
      app.kubernetes.io/instance: temps
    name: temps
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: temps:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: temps
      git:
        uri: https://github.com/RedHatTraining/DO180-apps
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.3
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: tJI5or7sxA2uQ1rcgFeZ
      type: GitHub
    - generic:
        secret: ZWFesDQMMQHoLTBnVqly
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: tempapp
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"temps:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"temps\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: temps
      app.kubernetes.io/component: temps
      app.kubernetes.io/instance: temps
    name: temps
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: temps
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: temps
      spec:
        containers:
        - image: ' '
          name: temps
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
- apiVersion: v1
  kind: Service
  metadata:
    namespace: tempapp
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: temps
      app.kubernetes.io/component: temps
      app.kubernetes.io/instance: temps
    name: temps
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: temps
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: temps
      app.kubernetes.io/component: temps
      app.kubernetes.io/instance: temps
    name: temps
    namespace: tempapp
  spec:
    host: tempapp.apps.ocp4.example.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: temps
      weight: 100
    wildcardPolicy: None
