apiVersion: v1
#kind: List
spec: {}
items:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: todoapp
  spec: {}
  status: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: todo
      app.kubernetes.io/component: todo
      app.kubernetes.io/instance: todo
    name: todo
    namespace: todoapp
  spec:
    host: todoapp.apps.ocp4.example.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: todo
      weight: 100
    wildcardPolicy: None
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    namespace: todoapp
    labels:
      app: todo
      app.kubernetes.io/component: todo
      app.kubernetes.io/instance: todo
    name: todo
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/redhattraining/todo-angular:v1.1
      from:
        kind: DockerImage
        name: quay.io/redhattraining/todo-angular:v1.1
      generation: null
      importPolicy: {}
      name: v1.1
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: todoapp
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"todo:v1.1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"todo\")].image"}]'
    labels:
      app: todo
      app.kubernetes.io/component: todo
      app.kubernetes.io/instance: todo
    name: todo
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: todo
    strategy: {}
    template:
      metadata:
        labels:
          deployment: todo
      spec:
        containers:
        - image: ' '
          name: todo
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    namespace: todoapp
    labels:
      app: todo
      app.kubernetes.io/component: todo
      app.kubernetes.io/instance: todo
    name: todo
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: todo
